# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: RProtocol.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fRProtocol.proto\"I\n\x10protocol_message\x12\x13\n\x03\x41\x63k\x18\x01 \x01(\x0b\x32\x04.ackH\x00\x12\x15\n\x04Nack\x18\x02 \x01(\x0b\x32\x05.nackH\x00\x42\t\n\x07message\"\x13\n\x03\x61\x63k\x12\x0c\n\x04resp\x18\x01 \x01(\r\"\x14\n\x04nack\x12\x0c\n\x04resp\x18\x01 \x01(\rb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'RProtocol_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PROTOCOL_MESSAGE._serialized_start=19
  _PROTOCOL_MESSAGE._serialized_end=92
  _ACK._serialized_start=94
  _ACK._serialized_end=113
  _NACK._serialized_start=115
  _NACK._serialized_end=135
# @@protoc_insertion_point(module_scope)
