# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: RRadsat.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import RProtocol_pb2 as proto_dot_RProtocol__pb2
from . import RTelecommands_pb2 as proto_dot_RTelecommands__pb2
from . import RFileTransfer_pb2 as proto_dot_RFileTransfer__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='RRadsat.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\rRRadsat.proto\x1a\x15proto/RProtocol.proto\x1a\x19proto/RTelecommands.proto\x1a\x19proto/RFileTransfer.proto\"\xb4\x01\n\x0eradsat_message\x12,\n\x0fProtocolMessage\x18\x01 \x01(\x0b\x32\x11.protocol_messageH\x00\x12\x35\n\x13\x46ileTransferMessage\x18\x02 \x01(\x0b\x32\x16.file_transfer_messageH\x00\x12\x32\n\x12TelecommandMessage\x18\x03 \x01(\x0b\x32\x14.telecommand_messageH\x00\x42\t\n\x07serviceb\x06proto3'
  ,
  dependencies=[proto_dot_RProtocol__pb2.DESCRIPTOR,proto_dot_RTelecommands__pb2.DESCRIPTOR,proto_dot_RFileTransfer__pb2.DESCRIPTOR,])




_RADSAT_MESSAGE = _descriptor.Descriptor(
  name='radsat_message',
  full_name='radsat_message',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ProtocolMessage', full_name='radsat_message.ProtocolMessage', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='FileTransferMessage', full_name='radsat_message.FileTransferMessage', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='TelecommandMessage', full_name='radsat_message.TelecommandMessage', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='service', full_name='radsat_message.service',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=95,
  serialized_end=275,
)

_RADSAT_MESSAGE.fields_by_name['ProtocolMessage'].message_type = proto_dot_RProtocol__pb2._PROTOCOL_MESSAGE
_RADSAT_MESSAGE.fields_by_name['FileTransferMessage'].message_type = proto_dot_RFileTransfer__pb2._FILE_TRANSFER_MESSAGE
_RADSAT_MESSAGE.fields_by_name['TelecommandMessage'].message_type = proto_dot_RTelecommands__pb2._TELECOMMAND_MESSAGE
_RADSAT_MESSAGE.oneofs_by_name['service'].fields.append(
  _RADSAT_MESSAGE.fields_by_name['ProtocolMessage'])
_RADSAT_MESSAGE.fields_by_name['ProtocolMessage'].containing_oneof = _RADSAT_MESSAGE.oneofs_by_name['service']
_RADSAT_MESSAGE.oneofs_by_name['service'].fields.append(
  _RADSAT_MESSAGE.fields_by_name['FileTransferMessage'])
_RADSAT_MESSAGE.fields_by_name['FileTransferMessage'].containing_oneof = _RADSAT_MESSAGE.oneofs_by_name['service']
_RADSAT_MESSAGE.oneofs_by_name['service'].fields.append(
  _RADSAT_MESSAGE.fields_by_name['TelecommandMessage'])
_RADSAT_MESSAGE.fields_by_name['TelecommandMessage'].containing_oneof = _RADSAT_MESSAGE.oneofs_by_name['service']
DESCRIPTOR.message_types_by_name['radsat_message'] = _RADSAT_MESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

radsat_message = _reflection.GeneratedProtocolMessageType('radsat_message', (_message.Message,), {
  'DESCRIPTOR' : _RADSAT_MESSAGE,
  '__module__' : 'RRadsat_pb2'
  # @@protoc_insertion_point(class_scope:radsat_message)
  })
_sym_db.RegisterMessage(radsat_message)


# @@protoc_insertion_point(module_scope)
