# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: RTelecommands.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='RTelecommands.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x13RTelecommands.proto\"\x98\x02\n\x13telecommand_message\x12 \n\tBeginPass\x18\x01 \x01(\x0b\x32\x0b.begin_passH\x00\x12\x31\n\x11\x42\x65ginFileTransfer\x18\x02 \x01(\x0b\x32\x14.begin_file_transferH\x00\x12\x30\n\x11\x43\x65\x61seTransmission\x18\x03 \x01(\x0b\x32\x13.cease_transmissionH\x00\x12\x32\n\x12ResumeTransmission\x18\x04 \x01(\x0b\x32\x14.resume_transmissionH\x00\x12\"\n\nUpdateTime\x18\x05 \x01(\x0b\x32\x0c.update_timeH\x00\x12\x17\n\x05Reset\x18\x06 \x01(\x0b\x32\x06.resetH\x00\x42\t\n\x07message\" \n\nbegin_pass\x12\x12\n\npassLength\x18\x01 \x01(\r\"#\n\x13\x62\x65gin_file_transfer\x12\x0c\n\x04resp\x18\x01 \x01(\r\"&\n\x12\x63\x65\x61se_transmission\x12\x10\n\x08\x64uration\x18\x01 \x01(\r\"#\n\x13resume_transmission\x12\x0c\n\x04resp\x18\x01 \x01(\r\"\x1f\n\x0bupdate_time\x12\x10\n\x08unixTime\x18\x01 \x01(\r\"\x8e\x01\n\x05reset\x12\x1f\n\x06\x64\x65vice\x18\x01 \x01(\x0e\x32\x0f.reset.device_t\x12\x0c\n\x04hard\x18\x02 \x01(\r\"V\n\x08\x64\x65vice_t\x12\x07\n\x03Obc\x10\x00\x12\x0f\n\x0bTransmitter\x10\x01\x12\x0c\n\x08Receiver\x10\x02\x12\x10\n\x0c\x41ntennaSideA\x10\x03\x12\x10\n\x0c\x41ntennaSideB\x10\x04\x62\x06proto3'
)



_RESET_DEVICE_T = _descriptor.EnumDescriptor(
  name='device_t',
  full_name='reset.device_t',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='Obc', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='Transmitter', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='Receiver', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='AntennaSideA', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='AntennaSideB', index=4, number=4,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=544,
  serialized_end=630,
)
_sym_db.RegisterEnumDescriptor(_RESET_DEVICE_T)


_TELECOMMAND_MESSAGE = _descriptor.Descriptor(
  name='telecommand_message',
  full_name='telecommand_message',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='BeginPass', full_name='telecommand_message.BeginPass', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='BeginFileTransfer', full_name='telecommand_message.BeginFileTransfer', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='CeaseTransmission', full_name='telecommand_message.CeaseTransmission', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ResumeTransmission', full_name='telecommand_message.ResumeTransmission', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='UpdateTime', full_name='telecommand_message.UpdateTime', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Reset', full_name='telecommand_message.Reset', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='message', full_name='telecommand_message.message',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=24,
  serialized_end=304,
)


_BEGIN_PASS = _descriptor.Descriptor(
  name='begin_pass',
  full_name='begin_pass',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='passLength', full_name='begin_pass.passLength', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=306,
  serialized_end=338,
)


_BEGIN_FILE_TRANSFER = _descriptor.Descriptor(
  name='begin_file_transfer',
  full_name='begin_file_transfer',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='resp', full_name='begin_file_transfer.resp', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=340,
  serialized_end=375,
)


_CEASE_TRANSMISSION = _descriptor.Descriptor(
  name='cease_transmission',
  full_name='cease_transmission',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='duration', full_name='cease_transmission.duration', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=377,
  serialized_end=415,
)


_RESUME_TRANSMISSION = _descriptor.Descriptor(
  name='resume_transmission',
  full_name='resume_transmission',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='resp', full_name='resume_transmission.resp', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=417,
  serialized_end=452,
)


_UPDATE_TIME = _descriptor.Descriptor(
  name='update_time',
  full_name='update_time',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='unixTime', full_name='update_time.unixTime', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=454,
  serialized_end=485,
)


_RESET = _descriptor.Descriptor(
  name='reset',
  full_name='reset',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='device', full_name='reset.device', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='hard', full_name='reset.hard', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _RESET_DEVICE_T,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=488,
  serialized_end=630,
)

_TELECOMMAND_MESSAGE.fields_by_name['BeginPass'].message_type = _BEGIN_PASS
_TELECOMMAND_MESSAGE.fields_by_name['BeginFileTransfer'].message_type = _BEGIN_FILE_TRANSFER
_TELECOMMAND_MESSAGE.fields_by_name['CeaseTransmission'].message_type = _CEASE_TRANSMISSION
_TELECOMMAND_MESSAGE.fields_by_name['ResumeTransmission'].message_type = _RESUME_TRANSMISSION
_TELECOMMAND_MESSAGE.fields_by_name['UpdateTime'].message_type = _UPDATE_TIME
_TELECOMMAND_MESSAGE.fields_by_name['Reset'].message_type = _RESET
_TELECOMMAND_MESSAGE.oneofs_by_name['message'].fields.append(
  _TELECOMMAND_MESSAGE.fields_by_name['BeginPass'])
_TELECOMMAND_MESSAGE.fields_by_name['BeginPass'].containing_oneof = _TELECOMMAND_MESSAGE.oneofs_by_name['message']
_TELECOMMAND_MESSAGE.oneofs_by_name['message'].fields.append(
  _TELECOMMAND_MESSAGE.fields_by_name['BeginFileTransfer'])
_TELECOMMAND_MESSAGE.fields_by_name['BeginFileTransfer'].containing_oneof = _TELECOMMAND_MESSAGE.oneofs_by_name['message']
_TELECOMMAND_MESSAGE.oneofs_by_name['message'].fields.append(
  _TELECOMMAND_MESSAGE.fields_by_name['CeaseTransmission'])
_TELECOMMAND_MESSAGE.fields_by_name['CeaseTransmission'].containing_oneof = _TELECOMMAND_MESSAGE.oneofs_by_name['message']
_TELECOMMAND_MESSAGE.oneofs_by_name['message'].fields.append(
  _TELECOMMAND_MESSAGE.fields_by_name['ResumeTransmission'])
_TELECOMMAND_MESSAGE.fields_by_name['ResumeTransmission'].containing_oneof = _TELECOMMAND_MESSAGE.oneofs_by_name['message']
_TELECOMMAND_MESSAGE.oneofs_by_name['message'].fields.append(
  _TELECOMMAND_MESSAGE.fields_by_name['UpdateTime'])
_TELECOMMAND_MESSAGE.fields_by_name['UpdateTime'].containing_oneof = _TELECOMMAND_MESSAGE.oneofs_by_name['message']
_TELECOMMAND_MESSAGE.oneofs_by_name['message'].fields.append(
  _TELECOMMAND_MESSAGE.fields_by_name['Reset'])
_TELECOMMAND_MESSAGE.fields_by_name['Reset'].containing_oneof = _TELECOMMAND_MESSAGE.oneofs_by_name['message']
_RESET.fields_by_name['device'].enum_type = _RESET_DEVICE_T
_RESET_DEVICE_T.containing_type = _RESET
DESCRIPTOR.message_types_by_name['telecommand_message'] = _TELECOMMAND_MESSAGE
DESCRIPTOR.message_types_by_name['begin_pass'] = _BEGIN_PASS
DESCRIPTOR.message_types_by_name['begin_file_transfer'] = _BEGIN_FILE_TRANSFER
DESCRIPTOR.message_types_by_name['cease_transmission'] = _CEASE_TRANSMISSION
DESCRIPTOR.message_types_by_name['resume_transmission'] = _RESUME_TRANSMISSION
DESCRIPTOR.message_types_by_name['update_time'] = _UPDATE_TIME
DESCRIPTOR.message_types_by_name['reset'] = _RESET
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

telecommand_message = _reflection.GeneratedProtocolMessageType('telecommand_message', (_message.Message,), {
  'DESCRIPTOR' : _TELECOMMAND_MESSAGE,
  '__module__' : 'RTelecommands_pb2'
  # @@protoc_insertion_point(class_scope:telecommand_message)
  })
_sym_db.RegisterMessage(telecommand_message)

begin_pass = _reflection.GeneratedProtocolMessageType('begin_pass', (_message.Message,), {
  'DESCRIPTOR' : _BEGIN_PASS,
  '__module__' : 'RTelecommands_pb2'
  # @@protoc_insertion_point(class_scope:begin_pass)
  })
_sym_db.RegisterMessage(begin_pass)

begin_file_transfer = _reflection.GeneratedProtocolMessageType('begin_file_transfer', (_message.Message,), {
  'DESCRIPTOR' : _BEGIN_FILE_TRANSFER,
  '__module__' : 'RTelecommands_pb2'
  # @@protoc_insertion_point(class_scope:begin_file_transfer)
  })
_sym_db.RegisterMessage(begin_file_transfer)

cease_transmission = _reflection.GeneratedProtocolMessageType('cease_transmission', (_message.Message,), {
  'DESCRIPTOR' : _CEASE_TRANSMISSION,
  '__module__' : 'RTelecommands_pb2'
  # @@protoc_insertion_point(class_scope:cease_transmission)
  })
_sym_db.RegisterMessage(cease_transmission)

resume_transmission = _reflection.GeneratedProtocolMessageType('resume_transmission', (_message.Message,), {
  'DESCRIPTOR' : _RESUME_TRANSMISSION,
  '__module__' : 'RTelecommands_pb2'
  # @@protoc_insertion_point(class_scope:resume_transmission)
  })
_sym_db.RegisterMessage(resume_transmission)

update_time = _reflection.GeneratedProtocolMessageType('update_time', (_message.Message,), {
  'DESCRIPTOR' : _UPDATE_TIME,
  '__module__' : 'RTelecommands_pb2'
  # @@protoc_insertion_point(class_scope:update_time)
  })
_sym_db.RegisterMessage(update_time)

reset = _reflection.GeneratedProtocolMessageType('reset', (_message.Message,), {
  'DESCRIPTOR' : _RESET,
  '__module__' : 'RTelecommands_pb2'
  # @@protoc_insertion_point(class_scope:reset)
  })
_sym_db.RegisterMessage(reset)


# @@protoc_insertion_point(module_scope)
