# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: RTelecommands.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13RTelecommands.proto\"\x98\x02\n\x13telecommand_message\x12 \n\tBeginPass\x18\x01 \x01(\x0b\x32\x0b.begin_passH\x00\x12\x31\n\x11\x42\x65ginFileTransfer\x18\x02 \x01(\x0b\x32\x14.begin_file_transferH\x00\x12\x30\n\x11\x43\x65\x61seTransmission\x18\x03 \x01(\x0b\x32\x13.cease_transmissionH\x00\x12\x32\n\x12ResumeTransmission\x18\x04 \x01(\x0b\x32\x14.resume_transmissionH\x00\x12\"\n\nUpdateTime\x18\x05 \x01(\x0b\x32\x0c.update_timeH\x00\x12\x17\n\x05Reset\x18\x06 \x01(\x0b\x32\x06.resetH\x00\x42\t\n\x07message\" \n\nbegin_pass\x12\x12\n\npassLength\x18\x01 \x01(\r\"$\n\x13\x62\x65gin_file_transfer\x12\r\n\x05\x62\x65gin\x18\x01 \x01(\x08\"&\n\x12\x63\x65\x61se_transmission\x12\x10\n\x08\x64uration\x18\x01 \x01(\r\"%\n\x13resume_transmission\x12\x0e\n\x06resume\x18\x01 \x01(\x08\"\x1f\n\x0bupdate_time\x12\x10\n\x08unixTime\x18\x01 \x01(\r\"\x8e\x01\n\x05reset\x12\x1f\n\x06\x64\x65vice\x18\x01 \x01(\x0e\x32\x0f.reset.device_t\x12\x0c\n\x04hard\x18\x02 \x01(\r\"V\n\x08\x64\x65vice_t\x12\x07\n\x03Obc\x10\x00\x12\x0f\n\x0bTransmitter\x10\x01\x12\x0c\n\x08Receiver\x10\x02\x12\x10\n\x0c\x41ntennaSideA\x10\x03\x12\x10\n\x0c\x41ntennaSideB\x10\x04\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'RTelecommands_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _TELECOMMAND_MESSAGE._serialized_start=24
  _TELECOMMAND_MESSAGE._serialized_end=304
  _BEGIN_PASS._serialized_start=306
  _BEGIN_PASS._serialized_end=338
  _BEGIN_FILE_TRANSFER._serialized_start=340
  _BEGIN_FILE_TRANSFER._serialized_end=376
  _CEASE_TRANSMISSION._serialized_start=378
  _CEASE_TRANSMISSION._serialized_end=416
  _RESUME_TRANSMISSION._serialized_start=418
  _RESUME_TRANSMISSION._serialized_end=455
  _UPDATE_TIME._serialized_start=457
  _UPDATE_TIME._serialized_end=488
  _RESET._serialized_start=491
  _RESET._serialized_end=633
  _RESET_DEVICE_T._serialized_start=547
  _RESET_DEVICE_T._serialized_end=633
# @@protoc_insertion_point(module_scope)
